# Generated by Django 5.1.3 on 2025-02-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goods",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
